version: '3.8'

services:
  web:
    container_name: php_blog
    image: php:apache
    ports:
      - "3001:80"
    volumes:
      - /var/www/html:/var/www/html
    depends_on:
      - db
    networks:
      - app_network

  db:
    container_name: mysql_blog
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: database_blog
      MYSQL_USER: blog_user
      MYSQL_PASSWORD: BlogP@ssw0rd#2024!
      MYSQL_ROOT_PASSWORD: R00tP@ssw0rd#2024!
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
